services:
  client:
    image: mesher-client:latest
    build:
      context: ./mesher-client
      target: dev
    environment:
      NODE_ENV: prod
    ports:
      - 3000:3000
      - 9229:9299
    volumes:
    - ./mesher-client:/usr/src/client
    - /usr/src/client/node_modules
    - ./mesher-client/src:/usr/src/client/src