services:
  client:
    container_name: client
    image: ghcr.io/tsvetislavrangelov/mesher-web-client:master
    build:
      context: ./mesher-client
      target: final
    ports:
      - 3000:80
    labels:
      kompose.service.type: nodeport
      kompose.service.nodeport.port: 30000
      kompose.image-pull-policy: "Always"
  geometryGeneratorNonSampled:
    container_name: geometrygeneratornonsampled
    image: ghcr.io/tsvetislavrangelov/mesher-geometry-generator-nonsampled:master
    build:
      context: ./Services/GeometryGeneratorNonSampled
      target: final
    ports:
      - 8080:8080
    labels:
      kompose.image-pull-policy: "Always"
