apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: geometrygeneratornonsampled
spec:
  parentRefs:
    - name: eg
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: geometrygeneratornonsampled
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /api/GeometryNonSampled/GenerateVertices
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: generatorhistory
spec:
  parentRefs:
    - name: eg
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: generatorhistory
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /api/Model/SaveModel

