apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../deploy.yaml
    kompose.image-pull-policy: Always
    kompose.service.nodeport.port: "30000"
    kompose.service.type: nodeport
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: client
  name: client
spec:
  ports:
    - name: "3000"
      nodePort: 30000
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: client
  type: NodePort
