/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import { Text } from '@react-three/drei';

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/compressed.glb');
  return (
    <group {...props} dispose={null} scale={[0.1, 0.1, 0.1]} position={[0,-1.5, 0]}>
      
      <Text color="white" anchorX="center" anchorY="middle" position={[0,5,15]} scale={[5,5,5]}>
  United States Air Force
</Text>
<Text color="white" anchorX="center" anchorY="middle" position={[0,0,15]} scale={[5,5,5]}>
  A-11 Flying Helmet
</Text>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Headphones_low as Mesh).geometry}
        material={materials.GlassPlasticMat}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={580}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Lenses_low as Mesh).geometry}
        material={materials.LensesMat}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={580}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Leather1_low as Mesh).geometry}
        material={materials.LeatherPartsMat}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={580}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Metal1_low as Mesh).geometry}
        material={materials.MetalPartsMat}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={580}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Plastic1_low as Mesh).geometry}
        material={materials.RubberWoodMat}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={580}
      />
    </group>
  )
}

useGLTF.preload('/compressed.glb')