services:
  client:
    image: mesher-client:latest
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: prod
    ports:
      - 3000:3000
      - 9229:9299
    volumes:
    - .:/usr/src/client
    - /usr/src/client/node_modules
    - ./src:/usr/src/client/src