apiVersion: v1
kind: Service
metadata:
  name: postgres-hist
  labels:
    app: postgres-hist
spec:
  ports:
  - port: 5432
    name: postgres-hist
  clusterIP: None
  selector:
    app: postgres-hist
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-hist
spec:
  selector:
    matchLabels:
      app: postgres-hist
  serviceName: "postgres-hist"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-hist
    spec:
      containers:
      - name: postgres-hist
        image: postgres:13
        ports:
        - containerPort: 5432
          name: postgres-hist
        env:
        - name: POSTGRES_DB
          value: modeldb
        - name: POSTGRES_USER
          value: pguser
        - name: POSTGRES_PASSWORD
          value: S3curePassword!
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
