apiVersion: v1
kind: Service
metadata:
  name: mssql-gen-history
  labels:
    app: mssql-gen-history
spec:
  ports:
  - port: 1433
    name: mssql-gen-history
  selector:
    app: mssql-gen-history
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-gen-history
spec:
  selector:
    matchLabels:
      app: mssql-gen-history
  serviceName: "mssql-gen-history"
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql-gen-history
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
          name: mssql-gen-history
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  SA_PASSWORD: "czNjdXJlUGFzc3dvcmQhCg=="  # This is 'securePassword' base64 encoded
