name: CI

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            include:
              - dockerfile: ./Services/GeometryGeneratorNonSampled/Dockerfile
                image: ghcr.io/TsvetislavRangelov/mesher-geometry-generator-nonsampled
                working-directory: ./Services/GeometryGeneratorNonSampled
                service-name: GeometryGeneratorNonSampled
              - dockerfile: ./Services/GeneratorHistory/Dockerfile
                image: ghcr.io/TsvetislavRangelov/mesher-generator-history
                working-directory: ./Services/GeneratorHistory
                service-name: GeneratorHistory
              - dockerfile: ./Services/ModelCollection/Dockerfile
                image: ghcr.io/TsvetislavRangelov/mesher-model-collection
                working-directory: ./Services/ModelCollection
                service-name: ModelCollection
              - dockerfile: ./Services/Transactions/Dockerfile
                image: ghcr.io/TsvetislavRangelov/mesher-transactions
                working-directory: ./Services/Transactions
                service-name: Transactions
    name: Build and push container ${{matrix.service-name}}
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{matrix.image}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and Push Mesher Images
        uses: docker/build-push-action@v5
        with:
          context: ${{matrix.working-directory}}
          file: ${{matrix.dockerfile}}
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
