name: ci

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: mesher-client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CLIENT_TOKEN }}
      -
        name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prod
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ steps.meta.outputs.tags }}:latest
