name: Run Staging tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install AnyConnect VPN
        run: |
          sudo apt-get update
          sudo /sbin/modprobe tun
          sudo apt-get install openconnect
          printf 'Netlab Fontys ICT\n${{secrets.NETLAB_USER}}\n${{secrets.NETLAB_PASS}}\n' | sudo openconnect vpnnetlab.fhict.nl -b
          curl -v --header "Host: mesher.api" http://192.168.144.2/api/GeometryNonSampled/GenerateVertices
