name: Run Staging tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install AnyConnect VPN
        run: |
          sudo apt-get update
          sudo /sbin/modprobe tun
          sudo apt-get install openconnect
          printf '0\${{secrets.NETLAB_USER}}\${{secrets.NETLAB_PASS}}\ny\n' | /opt/cisco/anyconnect/bin/vpn -s connect vpnnetlab.fhict.nl
          ping 192.168.144.2
