name: Run Staging tests
on: push

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install AnyConnect VPN & Login
        run: |
          sudo apt-get update
          sudo /sbin/modprobe tun
          sudo apt-get install openconnect
          printf 'Netlab Fontys ICT\n${{secrets.NETLAB_USER}}\n${{secrets.NETLAB_PASS}}\n' | sudo openconnect vpnnetlab.fhict.nl -b

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 192.168.144.15 >> ~/.ssh/known_hosts
      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no student@192.168.144.15 "echo IT WORKS"
          echo "192.168.144.2 mesher.api" | sudo tee -a /etc/hosts
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
          cd mesher-client/tests
          k6 run geometry-generator-non-sampled-load-test.spec.ts
