name: Test

on:
  push:
    branches: ['master']

env:
  CODACY_API_TOKEN: ${{secrets.CODACY_API_TOKEN}}

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            include:
            - test-type: Unit
              script: ./run-unit.sh
              output-file: /Services/Tests/Unit/coverage.xml
    name: Run Tests (${{matrix.test-type}})
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        run: |
          sudo apt-get update && \
          sudo apt-get install -y dotnet-sdk-8.0
          export CODACY_PROJECT_TOKEN=${{CODACY_API_TOKEN}}
          bash ${{matrix.script}}
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ${{matrix.output-file}}
          
          
